name: 'Terraform plan'
description: 'Terraform plan on Pull Request'
inputs:
  working-directory:
    description: ''
    required: true
    default: '.'
  enable-lock:
    default: true
    required: false
outputs:
  plan-stdout:
    description: Plan stdout
    value: ${{ steps.plan.outputs.stdout }}
  plan-stderr:
    description: Plan stderr
    value: ${{ steps.plan.outputs.stderr }}
  plan-has-changes:
    description: A flat indicates that the plan command has changes
    value: ${{ steps.plan-exitcode.outputs.plan-has-changes }}
runs:
  using: composite
  steps:
    - run: terraform fmt -check -recursive
      id: fmt
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
    - run: terraform init
      id: init
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
    - run: terraform validate
      id: validate
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
    - run: |
        set +e
        terraform plan -detailed-exitcode -input=false -lock=${{ inputs.enable-lock }}
        set -e
      id: plan
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
    - run: |
        planExitcode=${{ steps.plan.outputs.exitcode }}
        if [ ${planExitcode} -eq 0 ]; then
          planHasChanges=false
        elif [ ${planExitcode} -eq 2 ]; then
          planHasChanges=true
        else
          exit ${planExitcode}
        fi
        echo ::set-output name=plan-has-changes::${planHasChanges}
      id: plan-exitcode
      working-directory: "${{ inputs.working-directory }}"
      shell: bash
